app/models.py
from typing import List

from flask_login import UserMixin
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

from app import login

class Student(db.Model, UserMixin):
    uwa_id = db.Column(db.String(8), primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    group_id = db.Column(db.Integer, db.ForeignKey('group.group_id'), nullable=True)
    password_hash = db.Column(db.String(128))

    group = db.relationship('Group', back_populates='students')

    def __repr__(self) -> str:
        return f'<Student {self.name} {self.uwa_id}>'
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_id(self):
        return self.uwa_id

@login.user_loader
def get_user(id):
    return Student.query.get(id)

class Group(db.Model):
    group_id = db.Column(db.Integer, primary_key=True)

    students = db.relationship(Student, back_populates='group')

app/forms.py
from wtforms import PasswordField, SelectField, StringField, SubmitField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    uwa_id = StringField("UWA ID", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

class CreateGroupForm(FlaskForm):
    groupSize = SelectField("Group size", choices=[2,3,4])
    student1 = StringField("Student 1 id", validators=[DataRequired()])
    student2 = StringField("Student 2 id", validators=[DataRequired()])
    student3 = StringField("Student 3 id")
    student4 = StringField("Student 4 id")
    submit = SubmitField("Create group")

app/__init__.py
from flask import Flask
from app.config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

flaskApp = Flask(__name__)
flaskApp.config.from_object(Config)
db = SQLAlchemy(flaskApp)
migrate = Migrate(flaskApp, db)
login = LoginManager(flaskApp)
login.login_view = 'login'

from app import models, routes

app/blueprints.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app import routes

app/controllers.py
from app.models import Group, Student
from app import db

class GroupCreationError(Exception):
    pass

def create_group(studentIDs):
    students = []
    missing_students = []
    for id in studentIDs:
        student = Student.query.get(id)
        if not student:
            missing_students.append(id)
        else:
            students.append(student)

    if missing_students:
        raise GroupCreationError("Not all students registered")
    
    all_unique = len(set(students)) == len(students)
    if not all_unique:
        raise GroupCreationError("Groups cannot contain duplicate students!")

    assignedStudents = []
    for student in students:
        if student.group:
            assignedStudents.append(student)

    if assignedStudents:
        message = ""
        for student in students:
            message += f"{student.name} ({student.uwa_id}) is already assigned to a group\n"
        raise GroupCreationError(message)

    group = Group()
    group.students = students

    db.session.add(group)
    db.session.commit()

app/routes.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import login_user
from app import flaskApp, db
from app.forms import CreateGroupForm, LoginForm
from app.models import Group, Student


@flaskApp.route("/")
@flaskApp.route("/login", methods=['get', 'post'])
def login():
    form = LoginForm()
    if request.method == 'GET':
        return render_template('login.html', form=form)

    studentID = form.uwa_id.data
    student = Student.query.get(studentID)
    if not student:
        flash(f'No student found with ID {studentID}', 'error')
        return render_template('login.html', form=form)

    password = form.password.data
    if not student.check_password(password):
        flash(f'Invalid password. Please try again.', 'error')
        return render_template('login.html', form=form)

    login_user(student)
    return redirect(url_for('groups'))

@flaskApp.route("/logout")
def logout():
    return None

@flaskApp.route("/groups")
def groups():
    all_groups = Group.query.all()
    return render_template('listGroups.html', groups=all_groups)


@flaskApp.route('/create')
def create():
    form = CreateGroupForm()
    return render_template('createGroup.html', form=form)
    
@flaskApp.route('/submit', methods=['post'])
def submit():
    form = CreateGroupForm()
    if not form.validate_on_submit():
        return render_template('createGroup.html', form=form)
    
    groupSize = int(form.groupSize.data)
    studentIDs = [
        form.student1.data,
        form.student2.data,
        form.student3.data,
        form.student4.data        
    ][:groupSize]

    students = [find_student_by_id(id) for id in studentIDs]
    if not all(students):
        return render_template('createGroup.html', form=form)
    
    all_unique = len(set(students)) == len(students)
    if not all_unique:
        flash("Groups cannot contain duplicate students!")
        return render_template('createGroup.html', form=form)

    all_free = True
    for student in students:
        if student.group:
            flash(f"{student.name} ({student.uwa_id}) is already assigned to a group")
            all_free = False

    if not all_free:
        return render_template('createGroup.html', form=form)

    group = Group()
    group.students = students

    db.session.add(group)
    db.session.commit()
    
    return redirect(location=url_for("groups"))

def find_student_by_id(id:str):
    student = Student.query.get(id)
    if not student:
        flash(f'Could not find student with UWA ID: {id}', 'error')
    return student

app/templates/createGroup.html
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/test.css">

    <script src="/static/test.js"></script>
  </head>
  <body>
    <div class="container">
      <div id="title">
        <h1> Group sign-up </h1>
      </div>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
          {% for message in messages %}
            <li> {{ message }} </li>
          {% endfor %}
        </ul>
        {% endif %}
      {% endwith %}

      <div id="signUpForm">
        <p> Enter your student numbers of the people in your group </p>
        <p> It is not required to have 4 people, you will be assigned members to fill out your group </p>
        <form action="/submit" method="post">
          {{ form.hidden_tag() }}

          {{ form.groupSize.label }}
          {{ form.groupSize }}
          <br>
          {{ form.student1.label }}
          {{ form.student1 }}
          <br>
          {{ form.student2.label }}
          {{ form.student2 }}
          <br>
          {{ form.student3.label }}
          {{ form.student3 }}
          <br>
          {{ form.student4.label }}
          {{ form.student4 }}
          <br>
          {{ form.submit() }}
        </form>

        <button class="btn btn-danger" onclick="location.href='{{ url_for('groups') }}'">
          <span class="fa fa-trash"></span> Cancel
        </button>
      </div>

    </div>
  </body>
</html>

app/templates/listGroups.html
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/test.css">

    <script src="/static/test.js"></script>
  </head>
  <body>
    <div class="container">
      <div id="title">
        <h1> Group projects </h1>
      </div>

      <div id="existingGroups">
        <h2> Existing groups</h2>
        <table>
          <tr>
            <th> Group ID </th>
            <th> Student1 </th>
            <th> Student2 </th>
            <th> Student3 </th>
            <th> Student4 </th>
          </tr>
          {% for group in groups %}
          <tr>
            <td> 0 </td>
            {% for student in group.students %}
            <td> <span class="studentName"> {{ student.name }} </span> ({{student.uwa_id}}) </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
      </div>

      <button class="btn btn-primary ejectButton" onclick="removeStudent()">
        <span class="fa fa-trash"></span> Remove student
      </button>


      <button class="btn btn-primary" onclick="location.href='{{ url_for('main.create') }}'">
        Create new group
      </button>
    </div>
  </body>
</html>

app/templates/login.html
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/test.css">

    <script src="/static/test.js"></script>
  </head>
  <body>
    <div class="container">
      <div id="title">
        <h1> Group sign-up login </h1>
      </div>

      {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
          {% for message in messages %}
            <li> {{ message }} </li>
          {% endfor %}
        </ul>
        {% endif %}
      {% endwith %}

      <div id="loginForm">
        <form action="/login" method="post">
          {{ form.hidden_tag() }}

          {{ form.uwa_id.label }}
          {{ form.uwa_id }}
          <br>
          {{ form.password.label }}
          {{ form.password }}
          <br>
          {{ form.submit() }}
        </form>

      </div>
    </div>
  </body>
</html>